### PR TITLE
PRSD-NONE: Remove redundant filter chain config

### PR DESCRIPTION
**Pull request by isobel-softwire**
Removes redundant filter chain config (made redundant by One Login mock)

### CODE REVIEW

**Review by JasminConterioSW — APPROVED** [review]
LGTM :)

**Comment by rowanhill** [comment]
Can you just explain why /lookup-an-address isn't needed any more?

**Comment by isobel-softwire** [comment]
> Can you just explain why /lookup-an-address isn't needed any more?

I put ` \lookup-an-address` in the filter chain to bypass authentication. The One Login mock now provides this authentication so putting the endpoint in the filter chain isn't needed.

**Comment by rowanhill** [comment]
Ah, okay - so how come we still need to permitAll() on /postcode and /register-as-a-landlord? (Perhaps the latter is the unauthenticated start page for the journey?)

**Comment by isobel-softwire** [comment]
Stubbed calls to OS Places are sent to localhost:8080/postcode - these calls don't require authentication. AFAIK you're right about /register-as-a-landlord

**Comment by rowanhill** [comment]
Ah, okay. I'd thought that /postcode might be the test page for making postcode requests, but that makes sense. Thanks!

**Pull request merged**
